import React from "react";
import AdminSidebar from "../Components/AdminSidebar";
import TableHOC from "../Components/TableHOC";

const arr = [
  {
    avatar: <img src={"https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/470.jpg"} alt="custImg" />,
    full_name: "Dwight Rosenbaum",
    gender: "female",
    email: "Maria95@hotmail.com",
    phone: "+1 (330) 184-2304",
    address: "19744 Quitzon Park",
    city: "Austynville",
    state: "Utah",
    country: "Grenada",
    zip: "2864738",
  },
  {
    avatar: <img src={"https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1220.jpg"} alt="custImg" />,
    full_name: "William Botsford III",
    gender: "male",
    email: "Kelvin.Keeling@hotmail.com",
    phone: "+1 (440) 590-7019",
    address: "4717 Durgan Green",
    city: "Fernebury",
    state: "Rhode Island",
    country: "Switzerland",
    zip: "1835691",
  },
  {
    avatar: <img src={"https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/604.jpg"} alt="custImg" />,
    full_name: "Willard Zemlak I",
    gender: "female",
    email: "Harriet76@yahoo.com",
    phone: "+1 (962) 419-7990",
    address: "524 Georgette Inlet",
    city: "West Kelly",
    state: "Maryland",
    country: "Bahamas",
    zip: "4997083",
  },
  {
    avatar: <img src={"https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/363.jpg"} alt="custImg" />,
    full_name: "Vicki Fisher-Ward",
    gender: "female",
    email: "Lynn.Kuhic@gmail.com",
    phone: "+1 (596) 894-8829",
    address: "2324 Schmidt Islands",
    city: "Draper",
    state: "Nevada",
    country: "Bonaire, Sint Eustatius and Saba",
    zip: "5810529",
  },
  {
    avatar: <img src={"https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/753.jpg"} alt="custImg" />,
    full_name: "Darryl Simonis",
    gender: "male",
    email: "Dustin_Bradtke@yahoo.com",
    phone: "+1 (995) 712-2284",
    address: "268 Williamson Brook",
    city: "Reston",
    state: "Indiana",
    country: "Cook Islands",
    zip: "9167326",
  },
  {
    avatar: <img src={"https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/931.jpg"} alt="custImg" />,
    full_name: "Dr. Brenda Fritsch",
    gender: "male",
    email: "Kelly_Friesen11@gmail.com",
    phone: "+1 (802) 370-6457",
    address: "5929 Trent Mountains",
    city: "Miracleton",
    state: "Florida",
    country: "Ukraine",
    zip: "9462837",
  },
  {
    avatar: <img src={"https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/487.jpg"} alt="custImg" />,
    full_name: "Ms. Rachel Buckridge",
    gender: "male",
    email: "Clinton2@yahoo.com",
    phone: "+1 (683) 287-3524",
    address: "20430 Jerrell Forges",
    city: "Rennerfort",
    state: "Kentucky",
    country: "Marshall Islands",
    zip: "1187467",
  },
  {
    avatar: <img src={"https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/297.jpg"} alt="custImg" />,
    full_name: "Dr. Hubert Hoeger",
    gender: "female",
    email: "Marion_Deckow49@gmail.com",
    phone: "+1 (311) 011-8221",
    address: "219 Satterfield Forges",
    city: "San Clemente",
    state: "Vermont",
    country: "Togo",
    zip: "7345295",
  },
  {
    avatar: <img src={"https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1060.jpg"} alt="custImg" />,
    full_name: "Santiago Aufderhar",
    gender: "male",
    email: "Archie.Stracke73@gmail.com",
    phone: "+1 (432) 920-8744",
    address: "6009 Trantow Ways",
    city: "Bernierbury",
    state: "Virginia",
    country: "Mayotte",
    zip: "8923522",
  },
  {
    avatar: <img src={"https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/19.jpg"} alt="custImg" />,
    full_name: "Merle Ledner",
    gender: "male",
    email: "Clinton75@gmail.com",
    phone: "+1 (429) 567-9315",
    address: "564 Isai Cove",
    city: "Elkhart",
    state: "Nebraska",
    country: "Faroe Islands",
    zip: "2885752",
  },
  {
    avatar: <img src={"https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/786.jpg"} alt="custImg" />,
    full_name: "Miss Yvonne Hammes III",
    gender: "male",
    email: "Rex92@gmail.com",
    phone: "+1 (346) 937-0371",
    address: "248 Nikki Throughway",
    city: "West Reynold",
    state: "Montana",
    country: "Niue",
    zip: "3070448",
  },
  {
    avatar: <img src={"https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1039.jpg"} alt="custImg" />,
    full_name: "Flora Waelchi",
    gender: "male",
    email: "Caleb_Stoltenberg@yahoo.com",
    phone: "+1 (265) 443-4002",
    address: "56705 Rogahn Shoals",
    city: "South Darrel",
    state: "North Dakota",
    country: "Australia",
    zip: "5355780",
  },
  {
    avatar: <img src={"https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1217.jpg"} alt="custImg" />,
    full_name: "Dr. Lucy Franey",
    gender: "female",
    email: "Courtney.Stanton27@gmail.com",
    phone: "+1 (081) 555-9503",
    address: "1639 Ryley Station",
    city: "Fort Merle",
    state: "Arizona",
    country: "Niger",
    zip: "3035481",
  },
  {
    avatar: <img src={"https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/246.jpg"} alt="custImg" />,
    full_name: "Kelvin West",
    gender: "male",
    email: "Roosevelt.Deckow@gmail.com",
    phone: "+1 (762) 889-2181",
    address: "690 Gutkowski Green",
    city: "Lake Lexieborough",
    state: "Kentucky",
    country: "Sri Lanka",
    zip: "8116322",
  },
  {
    avatar: <img src={"https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1018.jpg"} alt="custImg" />,
    full_name: "Rufus Corwin",
    gender: "female",
    email: "Danielle.Friesen83@hotmail.com",
    phone: "+1 (821) 318-9964",
    address: "14241 Brekke Shores",
    city: "Oak Lawn",
    state: "Illinois",
    country: "Switzerland",
    zip: "2430139",
  },
  {
    avatar: <img src={"https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1182.jpg"} alt="custImg" />,
    full_name: "Jack Jones",
    gender: "female",
    email: "Brittany.Stiedemann@hotmail.com",
    phone: "+1 (797) 420-1989",
    address: "602 Dickens Fords",
    city: "Waterloo",
    state: "Oklahoma",
    country: "Burkina Faso",
    zip: "8558782",
  },
  {
    avatar: <img src={"https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/4.jpg"} alt="custImg" />,
    full_name: "Dr. Cesar Roob",
    gender: "female",
    email: "Lula93@gmail.com",
    phone: "+1 (872) 812-4527",
    address: "9095 Schroeder Courts",
    city: "Windlercester",
    state: "Nebraska",
    country: "Suriname",
    zip: "3595368",
  },
  {
    avatar: <img src={"https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/493.jpg"} alt="custImg" />,
    full_name: "Ms. Marsha Larson",
    gender: "male",
    email: "Elbert.Welch@yahoo.com",
    phone: "+1 (805) 831-8623",
    address: "667 Erica Mountain",
    city: "North Kip",
    state: "Florida",
    country: "Australia",
    zip: "4136411",
  },
  {
    avatar: <img src={"https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1052.jpg"} alt="custImg" />,
    full_name: "Virgil Barton",
    gender: "female",
    email: "Cynthia.Purdy@gmail.com",
    phone: "+1 (724) 390-5129",
    address: "186 Bednar Cliffs",
    city: "Mayertview",
    state: "Arizona",
    country: "Afghanistan",
    zip: "9358278",
  },
  {
    avatar: <img src={"https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/579.jpg"} alt="custImg" />,
    full_name: "Rene Simonis IV",
    gender: "male",
    email: "Jeffrey.Rice58@hotmail.com",
    phone: "+1 (142) 235-7874",
    address: "8724 Kaley Crest",
    city: "Lake Gwen",
    state: "Idaho",
    country: "Kazakhstan",
    zip: "1313724",
  },
  {
    avatar: <img src={"https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/313.jpg"} alt="custImg" />,
    full_name: "Mildred Wunsch",
    gender: "male",
    email: "Eliseo66@yahoo.com",
    phone: "+1 (468) 036-3689",
    address: "78680 Mertz Neck",
    city: "Feilburgh",
    state: "Georgia",
    country: "Indonesia",
    zip: "5713091",
  },
  {
    avatar: <img src={"https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1148.jpg"} alt="custImg" />,
    full_name: "Joann Kemmer",
    gender: "male",
    email: "Eddie.Zemlak97@hotmail.com",
    phone: "+1 (703) 752-9449",
    address: "9158 Olaf Inlet",
    city: "Port Cathy",
    state: "West Virginia",
    country: "South Sudan",
    zip: "5745603",
  },
  {
    avatar: <img src={"https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1213.jpg"} alt="custImg" />,
    full_name: "Mrs. Alvin Gusikowski",
    gender: "male",
    email: "Kathryn_Gleichner8@gmail.com",
    phone: "+1 (797) 650-3725",
    address: "5158 Kling Road",
    city: "McCluremouth",
    state: "New York",
    country: "Brunei",
    zip: "2912656",
  },
  {
    avatar: <img src={"https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/612.jpg"} alt="custImg" />,
    full_name: "Deborah Kohler",
    gender: "male",
    email: "Terrance.Cronin72@gmail.com",
    phone: "+1 (861) 038-3495",
    address: "8625 Rutherford Walks",
    city: "Marvinburgh",
    state: "Wisconsin",
    country: "Bolivia",
    zip: "1855997",
  },
  {
    avatar: <img src={"https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/309.jpg"} alt="custImg" />,
    full_name: "Mr. Allen Waelchi",
    gender: "male",
    email: "Elton_Stehr@gmail.com",
    phone: "+1 (379) 890-6141",
    address: "422 Wiza Wall",
    city: "East Savannah",
    state: "Rhode Island",
    country: "Tonga",
    zip: "6205390",
  },
  {
    avatar: <img src={"https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/983.jpg"} alt="custImg" />,
    full_name: "Mrs. Amanda Spencer",
    gender: "female",
    email: "Kasey.Casper30@gmail.com",
    phone: "+1 (698) 672-7650",
    address: "8600 Nellie Shoal",
    city: "Lake Jorge",
    state: "New Mexico",
    country: "Bosnia and Herzegovina",
    zip: "4884556",
  },
  {
    avatar: <img src={"https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/201.jpg"} alt="custImg" />,
    full_name: "Rosie Gulgowski",
    gender: "female",
    email: "Loraine56@yahoo.com",
    phone: "+1 (818) 900-7083",
    address: "66996 Heller Crest",
    city: "Bartellton",
    state: "Colorado",
    country: "Iceland",
    zip: "4658570",
  },
  {
    avatar: <img src={"https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1233.jpg"} alt="custImg" />,
    full_name: "Micheal Parisian",
    gender: "female",
    email: "Ora97@yahoo.com",
    phone: "+1 (468) 595-6087",
    address: "1709 Fadel Loop",
    city: "Port Delphineview",
    state: "Texas",
    country: "Greenland",
    zip: "6007595",
  },
  {
    avatar: <img src={"https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/193.jpg"} alt="custImg" />,
    full_name: "Norma Rath",
    gender: "female",
    email: "Adeline.Morissette@hotmail.com",
    phone: "+1 (663) 873-1697",
    address: "9023 Stiedemann Walks",
    city: "Port Aditya",
    state: "North Dakota",
    country: "Sweden",
    zip: "1305075",
  },
];

const columns = [
  {
    Header: "Avatar",
    accessor: "avatar",
  },
  {
    Header: "Full Name",
    accessor: "full_name",
  },
  {
    Header: "Gender",
    accessor: "gender",
  },
  {
    Header: "Email",
    accessor: "email",
  },
  {
    Header: "Phone",
    accessor: "phone",
  },
  {
    Header: "Address",
    accessor: "address",
  },
  {
    Header: "City",
    accessor: "city",
  },
  {
    Header: "State",
    accessor: "state",
  },
  {
    Header: "Country",
    accessor: "country",
  },
  {
    Header: "Zip",
    accessor: "zip",
  },
];

function Customers() {
  const data = arr;
  const table = TableHOC(columns, data, "customerBox", "Customers", true, 5);

  return (
    <div className="adminContainer">
      <div className="sideNavBar">
        <AdminSidebar />
      </div>
      <main className="dashboard">
        <div
          id="mainlogo"
          style={{
            display: "none",
            textAlign: "center",
            fontSize: "3rem",
            fontWeight: "700",
          }}
        >
          Logo.
        </div>
        <div className="customerContainer">{table()}</div>
      </main>
    </div>
  );
}

export default Customers;
